version: '3.5'
services:
  zuni-api-sevice:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'ghcr.io/dv-lab/zuni-backend3:latest'
    container_name: zuni-backend3
    ports:
      - 5000:5000
    volumes:
      - ./.env:/app/.env
      - ./jwt-private-key.key:/app/jwt-private-key.key
    restart: always
