name: Release & deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # Image name MUST have a pattern like <org_name_lowercase>/<repo_name_lowercase>
  IMAGE_NAME: dv-lab/zuni-backend3

  CD_USERNAME: ${{ github.actor }}

jobs:
  # Use if need to build package
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.CD_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}

          # TODO: Remove docker volumes in Dev stage only
          script: |
            export CR_PAT=${{ secrets.GITHUB_TOKEN }}
            echo $CR_PAT | docker login ${{ env.REGISTRY }} -u ${{ env.CD_USERNAME }} --password-stdin
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

            mkdir -p zuni/zuni-backend3
            cd $HOME/zuni/zuni-backend3
            rm -f .env
            echo MONGODB_URI=${{ secrets.MONGODB_URI }} >> .env
            echo PORT=${{ secrets.PORT }} >> .env
            echo AWS_S3_ACCESS_KEY_ID=${{ secrets.AWS_S3_ACCESS_KEY_ID }} >> .env
            echo AWS_S3_SECRET_ACCESS_KEY=${{ secrets.AWS_S3_SECRET_ACCESS_KEY }} >> .env
            echo AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }} >> .env
            echo AWS_S3_REGION=${{ secrets.AWS_S3_REGION }} >> .env
            echo VERIFIABLE_DATA_REGISTRY_PROGRAM_ID=${{ secrets.VERIFIABLE_DATA_REGISTRY_PROGRAM_ID }} >> .env
            curl -s https://${{ secrets.SUPER_ACCESS_TOKEN }}@raw.githubusercontent.com/dv-lab/zuni-backend3/main/docker-compose.yml -o docker-compose.yml
            docker-compose down
            docker-compose up -d
            docker logout ${{ env.REGISTRY }}
            